PL/Controllers/EstadisticaController.cs
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    public class EstadisticaController : Controller
    {
        [HttpGet]
        public IActionResult GetAll()
        {
            
            ML.Cine cine = new ML.Cine();
            cine.Cines = new List<object>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:5122/api/");
                var responseTask = client.GetAsync("Cine");
                responseTask.Wait();
                var resultService = responseTask.Result;
                if (resultService.IsSuccessStatusCode)
                {
                    var readTask = resultService.Content.ReadAsAsync<ML.Result>();
                    readTask.Wait();
                    foreach (var resultCine in readTask.Result.Objects)
                    {
                        ML.Cine resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Cine>(resultCine.ToString());
                        cine.Cines.Add(resultItemList);
                    }
                }
            }
            return View(cine);
        }
    }
}

PL/Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using System.Linq;
using System.Net.Http;

namespace PL.Controllers
{
    public class MovieController : Controller
    {
        [HttpGet]
        public IActionResult GetAll()
        {
            
            Models.Root root = new Models.Root();
            root.results = new List<Models.Movie>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://api.themoviedb.org/3/movie/popular");
                var responseTask = client.GetAsync("?api_key=31e541d91f4612df7a43bcaf3cfe4be3");
                responseTask.Wait();

                var resultService = responseTask.Result;
                if (resultService.IsSuccessStatusCode)
                {
                    var readTask = resultService.Content.ReadAsAsync<Models.Root>();
                    readTask.Wait();
                    foreach (var resultMovie in readTask.Result.results)
                    {
                        root.results.Add(resultMovie);

                    }
                }


            }

            return View(root);
        }
        [HttpGet]
        public ActionResult GetAllSin(int? page)
        {

            Models.MovieS movieS = new Models.MovieS();

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://api.themoviedb.org/3/movie/popular");
                //var responseTask = client.GetAsync("");
                string url = "";
                //if (page == null)
                //{
                    page = page==null ? 1:page;
                    url = "?api_key=31e541d91f4612df7a43bcaf3cfe4be3&page=" + page;
                //}
                var responseTask = client.GetAsync(url);
                responseTask.Wait();

                var resultService = responseTask.Result;
                if (resultService.IsSuccessStatusCode)
                {
                    var readTask = resultService.Content.ReadAsStringAsync();
                    dynamic resultJSON = JObject.Parse(readTask.Result.ToString());
                    readTask.Wait();
                    movieS.Movies = new List<object>();
                    foreach (var resultItem in resultJSON.results)
                    {
                        Models.MovieS movieItem = new Models.MovieS();
                   
                        movieItem.id = resultItem.id;
                        movieItem.title = resultItem.title;
                        movieItem.release_date = resultItem.release_date;
                        movieItem.original_title = resultItem.original_title;
                        movieItem.overview = resultItem.overview;
                        movieItem.popularity = resultItem.popularity;
                        movieItem.backdrop_path = "https://www.themoviedb.org/t/p/w300_and_h450_bestv2/" + resultItem.backdrop_path;
                        movieS.Movies.Add(movieItem);

                    }
                }


            }
            ViewBag.page = page;
            return View(movieS);
        }
        
        
        public ActionResult AddFavorite(int IdMovie, bool Favorite)
        {
            
            using (var client = new HttpClient())
            {
  
                client.BaseAddress = new Uri("https://api.themoviedb.org/3/account/");
                var json = new
                {
                    media_type = "movie",
                    media_id = IdMovie,
                    favorite = Favorite
                };
                var postTask = client.PostAsJsonAsync("20522403/favorite?session_id=4daa41461d611b36e69708ce658629a4f87c3595&api_key=31e541d91f4612df7a43bcaf3cfe4be3",json);
                postTask.Wait();
                var resultMovie=postTask.Result;
                if (Favorite)
                {
                    if (resultMovie.IsSuccessStatusCode)
                    {
                        ViewBag.Mensaje = "Agregado a favoritos";
                    }
                }
                else
                {
                    if (resultMovie.IsSuccessStatusCode)
                    {
                        ViewBag.Mensaje = "Eliminado de favoritos";
                    }
                }
                
                return View("Modal");
            }
        }

        public ActionResult GetAllFavorite(int? page)
        {
            Models.MovieS movieS = new Models.MovieS();
            using (var client = new HttpClient())
            {

                client.BaseAddress = new Uri("https://api.themoviedb.org/3/");

                string url = "";
                if (page == null)
                {
                    url = "account/20522454/favorite/movies?api_key=31e541d91f4612df7a43bcaf3cfe4be3&session_id=4daa41461d611b36e69708ce658629a4f87c3595";
                }



                var responseTask = client.GetAsync(url);
                responseTask.Wait();

                var resultService = responseTask.Result;
                if (resultService.IsSuccessStatusCode)
                {
                    var readTask = resultService.Content.ReadAsStringAsync();
                    dynamic resultJSON = JObject.Parse(readTask.Result.ToString());
                    readTask.Wait();
                    movieS.Movies = new List<object>();
                    foreach (var resultItem in resultJSON.results)
                    {
                        Models.MovieS movieItem = new Models.MovieS();
                        movieItem.id = resultItem.id;
                        movieItem.title = resultItem.title;
                        movieItem.release_date = resultItem.release_date;
                        movieItem.original_title = resultItem.original_title;
                        movieItem.overview = resultItem.overview;
                        movieItem.popularity = resultItem.popularity;
                        movieItem.backdrop_path = "https://www.themoviedb.org/t/p/w300_and_h450_bestv2/" + resultItem.backdrop_path;
                        movieS.Movies.Add(movieItem);

                    }
                }
            }
            ViewBag.page = page;
            return View(movieS);
        }

    }
}

PL/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Net.Mail;
using System.Security.Cryptography;
using System.Text;
using System.Web;

namespace PL.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly IWebHostEnvironment _hostingEnvironment;

        public UsuarioController(IWebHostEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment;
        }
        public IActionResult Login()
        {
            return View();
        }
        public IActionResult CambiarPassword()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Login(ML.Usuario usuario, string Password)
        {
            //var passwordHash = GetSHA256Hash(Password);
            //var bcript = new Rfc2898DeriveBytes(Password, new byte[0], 1000, HashAlgorithmName.SHA256);
            //var passwordHash = bcript.GetBytes(20);
            byte[] inputBytes = Encoding.UTF8.GetBytes(Password);

            if (usuario.UserName != null)
            {
                usuario.Password = inputBytes;
                ML.Result result = BL.Usuario.Add(usuario);
                if (result.Correct)
                {
                    ViewBag.Mensaje = "Usuario Agregado correctamente";
                }
                else
                {
                    ViewBag.Mensaje = "No se agrego el usuario";
                }
                return PartialView("Modal");

            }
            else
            {
                ML.Result result = BL.Usuario.UsuarioGetByEmail(usuario.Email);
                usuario = (ML.Usuario)result.Object;
                var storedPassword = usuario.Password;
                if (inputBytes.SequenceEqual(storedPassword))
                {
                    return RedirectToAction("Index", "Home");
                }

            }
            return View();
        }


        [HttpPost]

        public IActionResult CambiarPassword(string Email)
        {
            //llamar al metodo
            string emailOrigen = "msandovalg00@gmail.com";

            MailMessage mailMessage = new MailMessage(emailOrigen, Email, "Recuperar Contraseña", "<p>Correo para recuperar contraseña</p>");
            mailMessage.IsBodyHtml = true;

            string contenidoHTML = System.IO.File.ReadAllText(Path.Combine(_hostingEnvironment.ContentRootPath, "wwwroot", "Templates", "Email.html"));


            mailMessage.Body = contenidoHTML;
            string url = "http://localhost:5101/Usuario/NewPassword?Email=" + HttpUtility.UrlEncode(Email);

            mailMessage.Body = mailMessage.Body.Replace("{Url}", url);
            SmtpClient smtpClient = new SmtpClient("smtp.gmail.com");
            smtpClient.EnableSsl = true;
            smtpClient.UseDefaultCredentials = false;
            smtpClient.Port = 587;
            smtpClient.Credentials = new System.Net.NetworkCredential(emailOrigen, "ptyqkrxifzsuvyox");

            smtpClient.Send(mailMessage);
            smtpClient.Dispose();

            ViewBag.Modal = "show";
            ViewBag.Mensaje = "Se ha enviado un correo de confirmación a tu correo electronico";
            return View();
        }
        [HttpGet]
        public ActionResult NewPassword(string Email)
        {
            ML.Usuario usuario = new ML.Usuario();
            usuario.Email = Email;
            return View(usuario);
        }
        [HttpPost]
        //public ActionResult NewPassword(string password, string email)
        public ActionResult NewPassword(ML.Usuario usuario,string password,string Email)
        {
            byte[] inputBytes = Encoding.UTF8.GetBytes(password);
            if (usuario.Email!=null)
            {
                ML.Result result1 = BL.Usuario.UsuarioGetByEmail(Email);
                if (result1.Correct)
                {
                    usuario = (ML.Usuario)result1.Object;
                }
            }
            usuario.Password=inputBytes;
            ML.Result result = BL.Usuario.Update(usuario);
            if (result.Correct)
            {
                ViewBag.Mensaje = "Contraseña Actualizada correctamente";
            }
            else
            {
                ViewBag.Mensaje = "No se actualizo la contraseña";
            }

            return PartialView("Modal");
        }
    }
}

PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PL.styles.css" asp-append-version="true" />
     <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="GetAll">Movies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="GetAllSin">Popular</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cine" asp-action="GetAll">Cine</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Estadistica" asp-action="GetAll">Estadistica</a>
                        </li>
                       @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Login">Login</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dulceria" asp-action="GetAll">Dulceria</a>
                        </li>
                         @if (Context.Session.GetString("Carrito") == null)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-secondary"  style="color: green;" asp-area="" asp-controller="Dulceria" asp-action="Carrito"><i class="fa-solid fa-cart-arrow-down"></i>Carrito()</a>
                                </li>
                            }
                            else
                            {
                                var ventaSession = Newtonsoft.Json.JsonConvert.DeserializeObject<List<object>>(Context.Session.GetString("Carrito"));
                                <li class="nav-item">
                                    <a class="nav-link text-secondary" style="color: green;" asp-area="" asp-controller="Dulceria" asp-action="Carrito"><i class="fa-solid fa-cart-arrow-down"></i>Carrito(@ventaSession.Count)</a>
                                </li>
                            }
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="GetAllFavorite">Favoritos</a>
                        </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>